# ---
# apiVersion: apps.open-cluster-management.io/v1
# kind: Subscription
# metadata:
#   name: letschat-secret
#   labels:
#     app: letschat
#   namespace: letschat
#   annotations:
#     apps.open-cluster-management.io/github-path: apps/letschat/shared-secrets
#     apps.open-cluster-management.io/github-branch: main
# spec:
#   channel: letschat-rhacm/letschat
#   placement:
#     placementRef:
#       kind: PlacementRule
#       name: letschat-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: letschat-app
  labels:
    app: letschat
  namespace: letschat-rhacm
  annotations:
    apps.open-cluster-management.io/github-path: apps/letschat/letschat-app/submariner
    apps.open-cluster-management.io/github-branch: main
spec:
  channel: letschat-rhacm/letschat
  placement:
    placementRef:
      kind: PlacementRule
      name: letschat-app-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: letschat-db
  labels:
    app: letschat
  namespace: letschat-rhacm
  annotations:
    apps.open-cluster-management.io/github-path: apps/letschat/mongodb/subm-RADAR
    apps.open-cluster-management.io/github-branch: main
spec:
  channel: letschat-rhacm/letschat
  placement:
    placementRef:
      kind: PlacementRule
      name: letschat-db-placement

