kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb
  labels:
    app: letschat-db
spec:
  volumeName: letschat-demo
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: ibm-spectrum-scale-sample
