---
    apiVersion: app.k8s.io/v1beta1
    kind: Application
    metadata:
      namespace: letschat-rhacm
      name: letschat
    spec:
      componentKinds:
        - group: apps.open-cluster-management.io
          kind: Subscription
      selector:
        matchExpressions:
          - key: app
            operator: In 
            values: 
              - letschat
