kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-shared-pv
spec:
  capacity:
    storage: 3Gi
  csi:
    driver: spectrumscale.csi.ibm.com
    volumeHandle: >-
      8274719981642943972;2403030A:61A7974F;filesetName=letschat-demo;path=/mnt/remote-hmcs-fs1/letschat-demo
  accessModes:
    - ReadWriteMany
  claimRef: null
  persistentVolumeReclaimPolicy: Delete
  storageClassName: letschat-rahcm-demo
  volumeMode: Filesystem
