apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: letschat-rhacm
resources:
- namespace.yaml
#- placementrule.yaml
- placement.yaml
- channel.yaml
- subscription.yaml
- application.yaml
- letschat-secret-policy.yaml