apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: letschat-secret-policy
  namespace: letschat-dr-demo
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: mongodb
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - letschat-dr-demo
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Secret
                apiVersion: v1
                metadata:
                  name: mongodb
                type: Opaque
                data: '{{hub copySecretData "letschat-dr-demo" "mongodb" hub}}'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: letschat-secret-policy-placement-binding
  namespace: letschat-dr-demo
placementRef:
  name: default
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: letschat-secret-policy
    apiGroup: policy.open-cluster-management.io
    kind: Policy