---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: sitea
  namespace: letschat-dr-demo
spec:
  numberOfClusters: 1
  clusterSets:
  - dr-demo
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: site
          operator: In
          values:
          - a
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: siteb
  namespace: letschat-dr-demo
spec:
  numberOfClusters: 1
  clusterSets:
  - dr-demo
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: site
          operator: In
          values:
          - b
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: dr-demo
  namespace: letschat-dr-demo
spec:
  clusterSets:
  - dr-demo
